/** Original editable vector sources. Dimensions are SVG pixels, not gameplay units.
 * Body collision ignores decorative legs, antennae, wings, and the propulsion puff.
 * Caps remain at their natural ratio; stretch the separately rendered stems only.
 */
export const ART = Object.freeze({
  "beetle": { url: new URL("../../assets/art/beetle.svg", import.meta.url).href, viewBox: [256, 256], anchor: [0.5, 0.5], bodyBounds: [30, 55, 198, 143], collisionBounds: [43, 69, 170, 118], layers: ["far-legs", "antennae", "abdomen", "near-legs", "thorax", "head", "eyes"] },
  "beetle-flap": { url: new URL("../../assets/art/beetle-flap.svg", import.meta.url).href, viewBox: [256, 256], anchor: [0.5, 0.5], bodyBounds: [30, 55, 198, 143], collisionBounds: [43, 69, 170, 118], pose: "flap" },
  "beetle-fall": { url: new URL("../../assets/art/beetle-fall.svg", import.meta.url).href, viewBox: [256, 256], anchor: [0.5, 0.5], bodyBounds: [30, 55, 198, 143], collisionBounds: [43, 69, 170, 118], pose: "fall" },
  "juice-drop": { url: new URL("../../assets/art/juice-drop.svg", import.meta.url).href, viewBox: [64, 64], anchor: [0.5, 0.5], decorative: true },
  "juice-splash": { url: new URL("../../assets/art/juice-splash.svg", import.meta.url).href, viewBox: [128, 128], anchor: [0.5, 0.5], decorative: true },
  "pillar-sprout-stem": { url: new URL("../../assets/art/pillar-sprout-stem.svg", import.meta.url).href, viewBox: [180, 240], anchor: [0.5, 0.5], visibleBounds: [5, 0, 170, 240], repeatY: true, tileHeight: 2.4, decorative: true },
  "pillar-reed-stem": { url: new URL("../../assets/art/pillar-reed-stem.svg", import.meta.url).href, viewBox: [180, 240], anchor: [0.5, 0.5], visibleBounds: [5, 0, 170, 240], repeatY: true, tileHeight: 2.4, decorative: true },
  "pillar-fern-stem": { url: new URL("../../assets/art/pillar-fern-stem.svg", import.meta.url).href, viewBox: [180, 240], anchor: [0.5, 0.5], visibleBounds: [5, 0, 170, 240], repeatY: true, tileHeight: 2.4, decorative: true },
  "pillar-mushroom-stem": { url: new URL("../../assets/art/pillar-mushroom-stem.svg", import.meta.url).href, viewBox: [180, 240], anchor: [0.5, 0.5], visibleBounds: [5, 0, 170, 240], repeatY: true, tileHeight: 2.4, decorative: true },
  "pillar-bud-stem": { url: new URL("../../assets/art/pillar-bud-stem.svg", import.meta.url).href, viewBox: [180, 240], anchor: [0.5, 0.5], visibleBounds: [5, 0, 170, 240], repeatY: true, tileHeight: 2.4, decorative: true },
  "pillar-vine-stem": { url: new URL("../../assets/art/pillar-vine-stem.svg", import.meta.url).href, viewBox: [180, 240], anchor: [0.5, 0.5], visibleBounds: [5, 0, 170, 240], repeatY: true, tileHeight: 2.4, decorative: true },
  "pillar-thorn-stem": { url: new URL("../../assets/art/pillar-thorn-stem.svg", import.meta.url).href, viewBox: [180, 240], anchor: [0.5, 0.5], visibleBounds: [5, 0, 170, 240], repeatY: true, tileHeight: 2.4, decorative: true },
  "pillar-eyes": { url: new URL("../../assets/art/pillar-eyes.svg", import.meta.url).href, viewBox: [128, 128], anchor: [0.5, 0.5], pivot: [64, 42], decorative: true },
  "pillar-mouth": { url: new URL("../../assets/art/pillar-mouth.svg", import.meta.url).href, viewBox: [128, 128], anchor: [0.5, 0.5], pivot: [68, 95], decorative: true },
  "pillar-leaf": { url: new URL("../../assets/art/pillar-leaf.svg", import.meta.url).href, viewBox: [128, 128], anchor: [0.5, 0.5], pivot: [64, 64], decorative: true },
  "flame-bottom": { url: new URL("../../assets/art/flame-bottom.svg", import.meta.url).href, viewBox: [180, 150], anchor: [0.5, 0.5], visibleBounds: [4, 5, 172, 145], tip: [90, 5], direction: "bottom", decorative: true },
  "flame-top": { url: new URL("../../assets/art/flame-top.svg", import.meta.url).href, viewBox: [180, 150], anchor: [0.5, 0.5], visibleBounds: [4, 0, 172, 145], tip: [90, 145], direction: "top", decorative: true },
  "pillar-face": { url: new URL("../../assets/art/pillar-face.svg", import.meta.url).href, viewBox: [128, 128], anchor: [0.5, 0.5], decorative: true },
  "wing": { url: new URL("../../assets/art/wing.svg", import.meta.url).href, viewBox: [256, 256], anchor: [0.5, 0.5], pivot: [131, 110], decorative: true },
  "puff": { url: new URL("../../assets/art/puff.svg", import.meta.url).href, viewBox: [160, 128], anchor: [0.95, 0.63], decorative: true },
  "stardust-glint": { url: new URL("../../assets/art/stardust-glint.svg", import.meta.url).href, viewBox: [128, 128], anchor: [0.5, 0.5], decorative: true },
  "garden": { url: new URL("../../assets/art/garden.svg", import.meta.url).href, viewBox: [720, 1280], anchor: [0.5, 0.5], decorative: true },
  "platform": { url: new URL("../../assets/art/platform.svg", import.meta.url).href, viewBox: [320, 128], anchor: [0.5, 0.5], decorative: true },
  "heal": { url: new URL("../../assets/art/heal.svg", import.meta.url).href, viewBox: [128, 128], anchor: [0.5, 0.5], visibleBounds: [22, 2, 83, 116], semantic: "heal" },
  "poison": { url: new URL("../../assets/art/poison.svg", import.meta.url).href, viewBox: [128, 128], anchor: [0.5, 0.5], visibleBounds: [5, 9, 115, 113], semantic: "poison" },
  "star": { url: new URL("../../assets/art/star.svg", import.meta.url).href, viewBox: [128, 128], anchor: [0.5, 0.5], visibleBounds: [0, 10, 118, 114], semantic: "star" },
  "beetle-hurt": { url: new URL("../../assets/art/beetle-hurt.svg", import.meta.url).href, viewBox: [256, 256], anchor: [0.5, 0.5], bodyBounds: [30, 55, 198, 143] },
  "beetle-dizzy": { url: new URL("../../assets/art/beetle-dizzy.svg", import.meta.url).href, viewBox: [256, 256], anchor: [0.5, 0.5], bodyBounds: [30, 55, 198, 143] },
  "sprout-bottom": { url: new URL("../../assets/art/sprout-bottom.svg", import.meta.url).href, viewBox: [180, 150], anchor: [0.5, 0.5], visibleBounds: [4, 5, 172, 145], tip: [90, 5], direction: "bottom", capHeight: 1.48 },
  "sprout-top": { url: new URL("../../assets/art/sprout-top.svg", import.meta.url).href, viewBox: [180, 150], anchor: [0.5, 0.5], visibleBounds: [4, 0, 172, 145], tip: [90, 145], direction: "top", capHeight: 1.48 },
  "reed-bottom": { url: new URL("../../assets/art/reed-bottom.svg", import.meta.url).href, viewBox: [180, 150], anchor: [0.5, 0.5], visibleBounds: [4, 5, 172, 145], tip: [90, 5], direction: "bottom", capHeight: 1.48 },
  "reed-top": { url: new URL("../../assets/art/reed-top.svg", import.meta.url).href, viewBox: [180, 150], anchor: [0.5, 0.5], visibleBounds: [4, 0, 172, 145], tip: [90, 145], direction: "top", capHeight: 1.48 },
  "fern-bottom": { url: new URL("../../assets/art/fern-bottom.svg", import.meta.url).href, viewBox: [180, 150], anchor: [0.5, 0.5], visibleBounds: [4, 5, 172, 145], tip: [90, 5], direction: "bottom", capHeight: 1.48 },
  "fern-top": { url: new URL("../../assets/art/fern-top.svg", import.meta.url).href, viewBox: [180, 150], anchor: [0.5, 0.5], visibleBounds: [4, 0, 172, 145], tip: [90, 145], direction: "top", capHeight: 1.48 },
  "mushroom-bottom": { url: new URL("../../assets/art/mushroom-bottom.svg", import.meta.url).href, viewBox: [180, 150], anchor: [0.5, 0.5], visibleBounds: [4, 5, 172, 145], tip: [90, 5], direction: "bottom", capHeight: 1.48 },
  "mushroom-top": { url: new URL("../../assets/art/mushroom-top.svg", import.meta.url).href, viewBox: [180, 150], anchor: [0.5, 0.5], visibleBounds: [4, 0, 172, 145], tip: [90, 145], direction: "top", capHeight: 1.48 },
  "bud-bottom": { url: new URL("../../assets/art/bud-bottom.svg", import.meta.url).href, viewBox: [180, 150], anchor: [0.5, 0.5], visibleBounds: [4, 5, 172, 145], tip: [90, 5], direction: "bottom", capHeight: 1.48 },
  "bud-top": { url: new URL("../../assets/art/bud-top.svg", import.meta.url).href, viewBox: [180, 150], anchor: [0.5, 0.5], visibleBounds: [4, 0, 172, 145], tip: [90, 145], direction: "top", capHeight: 1.48 },
  "vine-bottom": { url: new URL("../../assets/art/vine-bottom.svg", import.meta.url).href, viewBox: [180, 150], anchor: [0.5, 0.5], visibleBounds: [4, 5, 172, 145], tip: [90, 5], direction: "bottom", capHeight: 1.48 },
  "vine-top": { url: new URL("../../assets/art/vine-top.svg", import.meta.url).href, viewBox: [180, 150], anchor: [0.5, 0.5], visibleBounds: [4, 0, 172, 145], tip: [90, 145], direction: "top", capHeight: 1.48 },
  "thorn-bottom": { url: new URL("../../assets/art/thorn-bottom.svg", import.meta.url).href, viewBox: [180, 150], anchor: [0.5, 0.5], visibleBounds: [4, 5, 172, 145], tip: [90, 5], direction: "bottom", capHeight: 1.48 },
  "thorn-top": { url: new URL("../../assets/art/thorn-top.svg", import.meta.url).href, viewBox: [180, 150], anchor: [0.5, 0.5], visibleBounds: [4, 0, 172, 145], tip: [90, 145], direction: "top", capHeight: 1.48 },
});

export const OBSTACLE_ART = Object.freeze([
  { id: "sprout", dangerKind: "thorn-sprout", stem: ART["pillar-sprout-stem"], bottom: ART["sprout-bottom"], top: ART["sprout-top"], stemColor: "#77c8a0", collisionWidth: 1.78, capHeight: 1.48 },
  { id: "reed", dangerKind: "needle-reed", stem: ART["pillar-reed-stem"], bottom: ART["reed-bottom"], top: ART["reed-top"], stemColor: "#a8bd8c", collisionWidth: 1.78, capHeight: 1.48 },
  { id: "fern", dangerKind: "razor-fern", stem: ART["pillar-fern-stem"], bottom: ART["fern-bottom"], top: ART["fern-top"], stemColor: "#8ac995", collisionWidth: 1.78, capHeight: 1.48 },
  { id: "mushroom", dangerKind: "toxic-needle-fungus", stem: ART["pillar-mushroom-stem"], bottom: ART["mushroom-bottom"], top: ART["mushroom-top"], stemColor: "#b5c791", collisionWidth: 1.78, capHeight: 1.48 },
  { id: "bud", dangerKind: "spike-seedpod", stem: ART["pillar-bud-stem"], bottom: ART["bud-bottom"], top: ART["bud-top"], stemColor: "#88bb8b", collisionWidth: 1.78, capHeight: 1.48 },
  { id: "vine", dangerKind: "burning-vine", flameBottom: "flame-bottom", flameTop: "flame-top", stem: ART["pillar-vine-stem"], bottom: ART["vine-bottom"], top: ART["vine-top"], stemColor: "#413745", collisionWidth: 1.78, capHeight: 1.48 },
  { id: "thorn", dangerKind: "twisted-thorn", stem: ART["pillar-thorn-stem"], bottom: ART["thorn-bottom"], top: ART["thorn-top"], stemColor: "#7ca994", collisionWidth: 1.78, capHeight: 1.48 },
]);
